services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  ragstar:
    build:
      context: .
    container_name: ragstar
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    environment:
      RAGSTAR_CONFIG_PATH: /app/ragstar.yaml
      RAGSTAR_OLLAMA_URL: http://ollama:11434/api/generate
      UV_CACHE_DIR: /app/.cache/uv
      XDG_CACHE_HOME: /app/.cache
      HOME: /app
    volumes:
      - ./ragstar.yaml:/app/ragstar.yaml:ro
      - ragstar-db:/app/ragstar_db

  ragstar-dev:
    image: python:3.12.8-slim
    container_name: ragstar-dev
    depends_on:
      - ollama
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "8001:8000"
    environment:
      RAGSTAR_CONFIG_PATH: /app/ragstar.yaml
      RAGSTAR_OLLAMA_URL: http://ollama:11434/api/generate
      HOME: /app
      UV_CACHE_DIR: /app/.cache/uv
      XDG_CACHE_HOME: /app/.cache
    volumes:
      - ./src:/app/src
      - dev-venv:/app/.venv
      - dev-cache:/app/.cache
      - ./pyproject.toml:/app/pyproject.toml:ro
      - ./README.md:/app/README.md:ro
      - ./uv.lock:/app/uv.lock:ro
      - ./ragstar.yaml:/app/ragstar.yaml:ro
      - ragstar-db:/app/ragstar_db
    working_dir: /app
    command: >
      sh -c "pip install uv && uv sync --frozen && uv run uvicorn ragstar.api:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/src"

volumes:
  ragstar-db:
  ollama-data:
  dev-venv:
  dev-cache:
