apiVersion: v1
kind: Service
metadata:
  name: ragstar
  namespace: ragstar
  labels:
    app: ragstar
spec:
  selector:
    app: ragstar
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8000
